version: '3.3'
services:
    db:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
            - SA_PASSWORD=Pass@word
        ports:
            - '5433:1433'
        image: mcr.microsoft.com/mssql/server:2019-latest
